name: GoCodeCheck

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.**'
    - 'LICENSE'
    - 'Makefile'
    - 'README.md'
    - '_script/**'

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Refresh report card
      run: |
        curl -d "repo=github.com/${{ github.repository }}" -X POST https://goreportcard.com/checks
