name: Release
on:
  release:
    types: [published]

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
    - name: Set GoVersion
      if: env.GoVersion == ''
      run: |
        echo "GoVersion=$(curl -s https://raw.githubusercontent.com/actions/go-versions/main/versions-manifest.json | grep -oEm 1 '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | cut -d':' -f2 | sed 's/ //g; s/"//g')" >> ${GITHUB_ENV}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GoVersion }}

    - name: Dep
      run: make dep

    - name: Build
      run: |
        make build TARGET=linux
        make build TARGET=windows

    - name: Upload Assets
      run: |
        gh release upload ${GITHUB_REF/refs\/tags\//} ${{ env.files }} --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # attribute
        files: justhealthreport justhealthreport.exe
